export const EVENT_LIST_REQUEST = "EVENT_LIST_REQUEST";
export const EVENT_LIST_SUCCESS = "EVENT_LIST_SUCCESS";
export const EVENT_LIST_FAIL = "EVENT_LIST_FAIL";

export const EVENT_FUTURE_LIST_REQUEST = "EVENT_FUTURE_LIST_REQUEST";
export const EVENT_FUTURE_LIST_SUCCESS = "EVENT_FUTURE_LIST_SUCCESS";
export const EVENT_FUTURE_LIST_FAIL = "EVENT_FUTURE_LIST_FAIL";

export const EVENT_WINNER_LIST_REQUEST = "EVENT_WINNER_LIST_REQUEST";
export const EVENT_WINNER_LIST_SUCCESS = "EVENT_WINNER_LIST_SUCCESS";
export const EVENT_WINNER_LIST_FAIL = "EVENT_WINNER_LIST_FAIL";

export const EVENT_GENERATE_REQUEST = "EVENT_GENERATE_REQUEST";
export const EVENT_GENERATE_SUCCESS = "EVENT_GENERATE_SUCCESS";
export const EVENT_GENERATE_FAIL = "EVENT_GENERATE_FAIL";
export const EVENT_GENERATE_RESET = "EVENT_GENERATE_RESET";

export const EVENT_FIND_WINNER_REQUEST = "EVENT_FIND_WINNER_REQUEST";
export const EVENT_FIND_WINNER_SUCCESS = "EVENT_FIND_WINNER_SUCCESS";
export const EVENT_FIND_WINNER_FAIL = "EVENT_FIND_WINNER_FAIL";
