export const EVENT_LIST_REQUEST = "EVENT_LIST_REQUEST";
export const EVENT_LIST_SUCCESS = "EVENT_LIST_SUCCESS";
export const EVENT_LIST_FAIL = "EVENT_LIST_FAIL";

export const EVENT_FUTURE_LIST_REQUEST = "EVENT_FUTURE_LIST_REQUEST";
export const EVENT_FUTURE_LIST_SUCCESS = "EVENT_FUTURE_LIST_SUCCESS";
export const EVENT_FUTURE_LIST_FAIL = "EVENT_FUTURE_LIST_FAIL";

export const EVENT_WINNER_LIST_REQUEST = "EVENT_WINNER_LIST_REQUEST";
export const EVENT_WINNER_LIST_SUCCESS = "EVENT_WINNER_LIST_SUCCESS";
export const EVENT_WINNER_LIST_FAIL = "EVENT_WINNER_LIST_FAIL";
