export const TICKET_LIST_REQUEST = "TICKET_LIST_REQUEST";
export const TICKET_LIST_SUCCESS = "TICKET_LIST_SUCCESS";
export const TICKET_LIST_FAIL = "TICKET_LIST_FAIL";

export const TICKET_BOOK_REQUEST = "TICKET_BOOK_REQUEST";
export const TICKET_BOOK_SUCCESS = "TICKET_BOOK_SUCCESS";
export const TICKET_BOOK_FAIL = "TICKET_BOOK_FAIL";

export const USER_TICKET_LIST_REQUEST = "USER_TICKET_LIST_REQUEST";
export const USER_TICKET_LIST_SUCCESS = "USER_TICKET_LIST_SUCCESS";
export const USER_TICKET_LIST_FAIL = "USER_TICKET_LIST_FAIL";
export const USER_TICKET_LIST_RESET = "USER_TICKET_LIST_RESET";
