export const TICKET_LIST_REQUEST = "TICKET_LIST_REQUEST";
export const TICKET_LIST_SUCCESS = "TICKET_LIST_SUCCESS";
export const TICKET_LIST_FAIL = "TICKET_LIST_FAIL";

export const TICKET_BOOK_REQUEST = "TICKET_BOOK_REQUEST";
export const TICKET_BOOK_SUCCESS = "TICKET_BOOK_SUCCESS";
export const TICKET_BOOK_FAIL = "TICKET_BOOK_FAIL";
